export ACK_OPTIONS='--no-color'
alias ls='ls -G'
alias l='ls'
alias ll='ls -al'
alias e='emacs'

alias gpl='git pull origin master'
alias pull='git pull'
alias gc='git checkout'
alias gb='git branch -v'
alias gd='git diff'
alias gst='git status'
alias gfp='git-format-patch'
alias gbb='git bisect bad'
alias gbg='git bisect good'
alias gl='git --no-pager log --pretty=format:"%h %ad | %s [%an]" --graph --date=short --max-count=15'

alias ss='rails server'
alias sg='rails generate'
alias sc='rails console'
alias sp='rails plugin'
alias s='shotgun'
alias mig='rake db:migrate'

alias rs='rake spec'

alias free='free -m'